export const DECKS = { 
    SELECTED: "USER_SELECTED_DECK", 
    GET: "GET_USER_DECKS", 
    CHOOSEN: "CHOOSEN_DECK", 
    ALL: "ALL_DECKS", 
    CARDS: "ALL_CARDS", 
    ADD: "ADD_DECK_NAME",
    UPDATE: "UPDATE_DECK",
    DELETE: "DELETE_DECK", 
};